### ISSUE TITLE
Capitalization and spacing in file paths

### ISSUE THREAD

**Issue by Red5d** [MycroftAI/adapt#47]
I'm attempting to write a tool to move files around using Adapt. I've used the regex intent example as a template and I'm encountering these problems:

Capitalization in input text is not preserved when getting the parsed values from the intent result object. (important for file/folder names)

File paths in the input are also shifted to lowercase and have spaces inserted around the slashes (/) in the file path.

**Comment by clusterfudge** [comment]
Any chance you can create a pull request with a unit test that reproduces the issue? 

Adapt is generally case insensitive (as the input is intended to be a speech recognizer, which typically have so-so casing capabilities). I think there's a case to be made for having case preserved on named entities, but regexes is a little stranger (should you match the string if the casing is wrong, or should you decide that on a per-regex basis?). 

Regular expressions do receive the tokenized text (as opposed to the literal string), so that might be tricky.

Sorry, stream of consciousness on the above a little bit, but a repro would definitely help. Also, if you're passing file name literals into adapt, I have to imagine you're not speaking them out loud. It's possible that for your use case it might make more sense to just construct the intent programmatically, as opposed to pushing it through a parser.

**Comment by Red5d** [comment]
I could check on creating a unit test for this.

I was intending on using Adapt for a text-based interface yes, though I'll note that Mycroft (primary use for Adapt) does have a CLI.

I did a quick test by cloning the Adapt repo, deleting all the .lower() calls in the code, then running my previously mentioned regex intent parser script, and it worked correctly with capitalization like that. Nothing seemed to break, though of course it *might* somewhere. 

If all text sent to Adapt by a speech recognizer would have the same letter case anyway (an assumption, I know), then are the .lower() calls actually necessary?

**Comment by clusterfudge** [comment]
Mycroft does have a CLI, though that's mostly for testing purposes at this time (I would know, I wrote it :)). 

With your modifications to adapt, likely things would match when cased correctly, and fail when cased incorrectly (think Band Name vs band name). Your use case seems pretty specific, so this may not matter to you. There may be room for a case-sensitive mode inside adapt, though tokenization (which would remove / characters) is something I'll still have to think about. 

Not all text sent to adapt via recognizer has the same case; it's inconsistent from recognizer to recognizer (IBM tries to be smarter with capitalization and punctuation for example, whereas google doesn't really try hard). For most command and control scenarios, case insensitive (and generally fuzzy) matching is preferable. If you're talking about literal unix commands, aliases and search within your skill will likely provide a better user experience (via voice), but again your use cases may differ.


Adapt is intended for natural language input, and things like literal file names don't (at least in my opinion) fall under that purview. I'm happy to see if we can make adapt work for your use case, but if I have to choose between this use case and general adapt quality/usability, I'll favor the latter.

**Comment by Red5d** [comment]
Ok, thanks for the explanation. I understand and don't want to create a lot of work for people just to fit my small use case.

**Comment by clusterfudge** [comment]
Not a problem, always excited to see what new use cases the community is coming up with!
